// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhuymbvkusvqqybhhkqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhodXltYnZrdXN2cXF5Ymhoa3F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MzU0MDAsImV4cCI6MjA2NDAxMTQwMH0.K9lU9NnpR35Eb1DK6UCnf91OM8YbJTxs12pJurOsoYE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);